#! /bin/sh
### BEGIN INIT INFO
# Provides: INR_FPGA_load
# Required-Start: $syslog
# Required-Stop: $syslog
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: Load userbitstream to FPGA on boot
# Description:
### END INIT INFO
 
case "$1" in
    start)
        /usr/share/InnoRoute/start.sh &
        ;;
    stop)
        echo "unloading user bitstream"
        /usr/share/InnoRoute/INR_write_bitstream /dev/null > /dev/null
        sudo rmmod INR_RTHAT

        ;;
    *)
        echo "Use: /etc/init.d/INR_FPGA_load {start|stop}"
        exit 1
        ;;
esac
 
exit 0
